travis:
  secure:
    BINSTAR_TOKEN: TXT2RzdBCVOYj3a5wuUC4YK6X1QLe4WuhZPQhCliV5mvS8BMb/mjoTiXseIhDzcZZNeZy6DLtBM3Sw5f0/ay1tZfO9RZjLDQMQ2JW5JKf6yrS/ITOLvU2/7TlD+ttY0rsPQu24c4NSd/AghnbEeo0DCHBl9UUT4BtTDV6Wb8iFF9FhL5uTkN8XuODoOkj0aq8+d1z4Up7uTn39c4fJgMPUOdSnobgc6Kj3JzjzHgV9JGc5bftX42DAyn1W0OjTwc+Anq8vyqCFWKTC34QPSYerPsfYjdIp6b1N9jdY0FIiortAIGf4EkVhtcgTONcL9OAoKYjD6232B+uBt5YiUOKP5qefpQsO4/vi3HPjhSnDzOqoryKebTXUyHjLgb3F2mzpKIZPY9oIjgiXxAYxubBcR51kIo+/INXgJW4c+FrBFIr8xtxeYJkrNeLteiQQEGjKYTVBfs+Lad0i8yBNBYY12G+b1+4bEgjpMim6XzfuDN/9KScoOhqNHiZ9hZKEMc8a1TwVzTHK1FSfFM2eVZxKa6ooWyjrXhprscUOW8NjtqPhQ3lMBZgqhi6Gg0SniuwAOFVA2H0H/9FD+1xokv+v5atw7aZFmDbBs0lzV+36XGCnLJmxY7sIyjCWLUAPdSLQjTBSPK363weCSnDNijxud8hW7+3UHUvPPyTaxQcI8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
