appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: v4Y4TkBq5zmnpeiq9fknCuw4Ksq8ck4Pj6SOKD9otf60EhCEdBo1yT0rfHvgaPIV8Jc6w8tOH2HDyQcmID65wErUzMB1CLr6Ly9Po0/nAeD9QHkL904jij3fePXlKWc/YsJu42DtnyJ49ONvRp9Org3I3bqSDMKfP38E37XOSbE2TncevzDskn0cl1wUd80fdcMEOjlDwoYGmWxtRVyh/OklzGeY4Pk+L8V96ZBSBcHq+wSj6NtvE48/Y65baSIBZjgw/izIxvAC0W4j+bVd2Fw7QiQ+PFH0zCVkZu0WEEQB8kdvqSg2XaSM03303r9Fk3oN5HbEZ7odBvocqIvXNTzWuAjmy51rh7PrFf6mk2W2O67rqhIMZHnJf8d752Y6jBq9O1doEyEzlkVNTBgseusd4ZQ9HB/VgPUxYOMlM0K+mnwBq3OLs8dF01fTgbSMLfD6okg3m1zukH5Gn6TowCz7CObBdaIzHS2VdYUU2W3cJCViKgMEzjr/M2BoX7MYddrNFfTniAxd2FNfimwVrYJEn0VjJ2C67A+ttf8NAQZOmYVIh5sZJPXtS4rdiqyBDF0nVkKsDrlLKCC31EbRUuKckhOeL/oRLRMbHkyz0Wshgu/T7QDRE7rPgqeQ8i3y7WxiRYzN2IhiaxRBy9FgMYYfaFYemr9HmgmebeLB9rs=}
